---
title: "Impact Initiatives: Analytical Process"
subtitle: "Statistics Without Borders 2024"
author: "Elham Ali"
format:
  revealjs:
    slide-number: true
    show-slide-number: all
    chalkboard: 
      buttons: false
    preview-links: true
    logo: images/swb.png
    footer: Published on January 4, 2024
    controls: true
editor: visual
---

## **Overview**

This presentation provides an review of findings from relevant analytical process documents from Impact Initiatives, best practices, and recommendations for improvement. The documents reviewed in this presentation are:

-   Guidelines_2-3_Quant Data Analysis_Annex3

-   Github: cleaningtools

-   Github: analysistools

-   Github: presentresults

## **Executive Summary**

TBD

## **Problem Statement**

The Impact Initiatives team have faced challenges to solve for the below pain points. This report aims to solve for these issues and provide best practices in general.

-   Handle missing data.

-   Correct size bias in the assessment.

-   Provide calibration techniques to help with better estimates.

## **Guidelines_2-3_Quant Data Analysis_Annex3**

## Github: cleaningtools

## Github: analysistools

## Github: presentresults

## 
